# Kafka configurations
inventory_name: kerberos

kafka_home: /opt/kafka/kafka_2.13-3.3.1

kafka_prereqs_setup_openjdk_package_name: java-11-openjdk

kafka_max_heap: 1G
kafka_min_heap: 1G

kafka_log4j_dir: /var/log/kafka
kafka_log_dirs:
  - /var/data/kafka

kafka_listeners:
  - name: SCRAM
    port: 9093
    tls: false
    authentication:
      type: scram-sha-512
  - name: GSSAPI
    port: 9094
    tls: false
    authentication:
      type: gssapi
      config:
        debug: "{{ kafka_jaas_debug }}"        
        useKeyTab: true
        storeKey: true
        keyTab: "{{ kafka_home }}/security/ansible_kafka.keytab"
        principal: "kafka/{{ inventory_hostname }}@EXAMPLE.REDHAT.COM"

kafka_authorization:
  type: simple
  deny_by_default: false
  super_users:
    - User:admin

kafka_inter_broker_listener_name: GSSAPI
kafka_admin_listener_name: GSSAPI

kafka_admin:
  listener_name: GSSAPI

kafka_additional_conf:
  auto.create.topics.enable: 'false'

kafka_skip_verify_under_replicated: true

kafka_jaas_debug: true

kafka_java_opts:
  - -Dsun.security.krb5.debug=true
