# Kafka configurations
inventory_name: plain

kafka_home: /opt/kafka/kafka_2.13-3.3.1

kafka_prereqs_setup_openjdk_package_name: java-11-openjdk

kafka_max_heap: 1G
kafka_min_heap: 1G

kafka_log4j_dir: /var/log/kafka
kafka_log_dirs:
  - /var/data/kafka

kafka_listeners:
  - name: PLAINTEXT
    port: 9092
    tls: false

kafka_additional_conf:
  auto.create.topics.enable: 'false'

kafka_skip_verify_under_replicated: true

